<?php
/**
 * HURON-PERTH CHILDREN'S AID SOCIETY LMS
 * SCORM Upload Background Runner (HTTP endpoint)
 *
 * Called asynchronously (fire-and-forget) by scorm-upload-handler.php via
 * a non-blocking HTTP request. Performs the slow work: ZIP extraction,
 * S3 upload, and manifest parsing.
 *
 * Security: protected by a one-time HMAC token stored in the job row.
 * The token is generated by the handler and verified here before processing.
 *
 * GET/POST ?job_id=N&token=HMAC
 *
 * This endpoint calls ignore_user_abort(true) and set_time_limit(0) so it
 * continues running after the caller disconnects.
 */

// ── Must be called via HTTP (not CLI) ──
if (PHP_SAPI === 'cli') {
    // Allow CLI invocation for manual testing / fallback
}

require_once __DIR__ . '/../bootstrap.php';
require_once __DIR__ . '/../scorm-api/scorm-normalize.php';

// Run independently of the caller — keep going even if the HTTP connection drops
ignore_user_abort(true);
set_time_limit(0);
ini_set('memory_limit', '512M');

// Flush headers immediately so the caller can disconnect.
// Skip this when required in-process by the upload handler (it already sent its
// own JSON response and finished the request).
if (empty($GLOBALS['_SCORM_INLINE'])) {
    if (!headers_sent()) {
        header('Content-Type: text/plain');
        header('Connection: close');
        header('Content-Length: 2');
    }
    echo 'OK';
    if (function_exists('fastcgi_finish_request')) {
        fastcgi_finish_request();
    } else {
        // Force output buffer flush so the HTTP response is sent
        $level = ob_get_level();
        while ($level-- > 0) {
            ob_end_flush();
        }
        flush();
    }
}

// ── Validate parameters ──
$jobId = (int)($_REQUEST['job_id'] ?? 0);
$token = (string)($_REQUEST['token'] ?? '');

if (!$jobId || !$token) {
    error_log('[RUN] Missing job_id or token');
    exit;
}

// ── Load job row and verify token ──
try {
    $pdo = getDbConnection();
    $stmt = $pdo->prepare("SELECT * FROM scorm_upload_jobs WHERE id=?");
    $stmt->execute([$jobId]);
    $job = $stmt->fetch(PDO::FETCH_ASSOC);
} catch (Throwable $e) {
    error_log('[RUN] DB error loading job: ' . $e->getMessage());
    exit;
}

if (!$job) {
    error_log('[RUN] Job not found: ' . $jobId);
    exit;
}

// Verify HMAC token
$expectedToken = hash_hmac('sha256', 'run:' . $jobId . ':' . $job['package_id'], APP_CSRF_SECRET);
if (!hash_equals($expectedToken, $token)) {
    error_log('[RUN] Invalid token for job ' . $jobId);
    exit;
}

// Atomically claim the job (queued → running). Only one worker may process it.
$claim = $pdo->prepare("UPDATE scorm_upload_jobs SET status='running', message='Starting extraction…', progress_pct=5, updated_at=NOW() WHERE id=? AND status='queued'");
$claim->execute([$jobId]);
if ($claim->rowCount() === 0) {
    error_log('[RUN] Job ' . $jobId . ' could not be claimed (current status: ' . $job['status'] . ')');
    exit;
}

$pkgId    = (int)$job['package_id'];
$stripPfx = (string)($job['strip_prefix'] ?? '');
$replaceFlag = (int)($job['replace_flag'] ?? 0);

// ── Helper: update job status ──
function jobUpdate(int $jobId, string $status, string $message = '', int $pct = 0, array $extra = []): void
{
    try {
        $pdo = getDbConnection();
        $pdo->prepare(
            "UPDATE scorm_upload_jobs SET status=?, message=?, progress_pct=?, updated_at=NOW() WHERE id=?"
        )->execute([$status, $message, $pct, $jobId]);
        if (!empty($extra)) {
            $sets = [];
            $vals = [];
            foreach ($extra as $col => $val) {
                $sets[] = "`$col`=?";
                $vals[] = $val;
            }
            $vals[] = $jobId;
            $pdo->prepare("UPDATE scorm_upload_jobs SET " . implode(',', $sets) . " WHERE id=?")->execute($vals);
        }
    } catch (Throwable $e) {
        error_log('[RUN] jobUpdate failed: ' . $e->getMessage());
    }
}

// ── Helper: rollback package row ──
function rollbackPkg(int $pkgId): void
{
    try {
        $pdo = getDbConnection();
        $pdo->prepare("DELETE FROM scorm_packages WHERE id=?")->execute([$pkgId]);
    } catch (Throwable $_) {}
}

// Replace mode: wipe the previous version of a package (keeps the package id).
function replaceCleanup(int $pkgId): void
{
    try {
        $pdo = getDbConnection();
        // Break the FK link so completed attempts survive the sco_items delete.
        $pdo->prepare("UPDATE scorm_attempts SET sco_item_id = NULL WHERE package_id = ?")->execute([$pkgId]);
        // Drop in-progress sessions so learners restart the new content cleanly.
        $pdo->prepare("DELETE FROM scorm_attempts WHERE package_id = ? AND is_complete = 0")->execute([$pkgId]);
        // Remove old SCO definitions.
        $pdo->prepare("DELETE FROM sco_items WHERE package_id = ?")->execute([$pkgId]);
    } catch (Throwable $e) {
        error_log('[REPLACE] DB cleanup error for pkg=' . $pkgId . ': ' . $e->getMessage());
    }

    // Local files.
    $dir = SCORM_STORAGE_PATH . '/' . $pkgId;
    if (is_dir($dir)) {
        $it = new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS);
        $files = new RecursiveIteratorIterator($it, RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($files as $f) {
            if ($f->isDir()) @rmdir($f->getRealPath());
            else @unlink($f->getRealPath());
        }
        @rmdir($dir);
    }

    // S3 objects.
    if (function_exists('isS3Configured') && isS3Configured()) {
        s3DeletePrefix(S3_PREFIX . $pkgId . '/');
    }

    // HTML rewrite cache for this package (per-user cache dirs).
    foreach (glob(rtrim(SCORM_CACHE_PATH, '/') . '/' . $pkgId . '_*') as $cDir) {
        if (!is_dir($cDir)) continue;
        $it2 = new RecursiveDirectoryIterator($cDir, FilesystemIterator::SKIP_DOTS);
        $f2 = new RecursiveIteratorIterator($it2, RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($f2 as $cf) {
            if ($cf->isDir()) @rmdir($cf->getRealPath());
            else @unlink($cf->getRealPath());
        }
        @rmdir($cDir);
    }

    error_log('[REPLACE] Previous content removed for pkg=' . $pkgId);
}

error_log("[RUN] Starting job=$jobId pkg=$pkgId strip='$stripPfx'");
jobUpdate($jobId, 'running', 'Starting extraction…', 5);

// ── Find the persisted temp file ──
$tmpPath = (string)($job['tmp_path'] ?? '');
if (!$tmpPath || !file_exists($tmpPath)) {
    jobUpdate($jobId, 'failed', 'Uploaded file not found on disk. Please try uploading again.', 0);
    if (!$replaceFlag) rollbackPkg($pkgId);
    exit;
}

// ── Step 1: Open ZIP ──
$zip = new ZipArchive();
if ($zip->open($tmpPath) !== true) {
    jobUpdate($jobId, 'failed', 'Could not open ZIP file.', 0);
    if (!$replaceFlag) rollbackPkg($pkgId);
    @unlink($tmpPath);
    exit;
}

// Replace mode: clear the previous version before extracting the new one.
if ($replaceFlag) {
    jobUpdate($jobId, 'running', 'Clearing previous package content...', 3);
    replaceCleanup($pkgId);
}

// ── Step 2: Extract ──
$packageDir = SCORM_STORAGE_PATH . '/' . $pkgId;
if (!is_dir($packageDir)) {
    mkdir($packageDir, 0755, true);
}

$extractedCount = 0;
try {
    jobUpdate($jobId, 'running', 'Extracting files…', 10);
    if ($stripPfx === '') {
        if (!$zip->extractTo($packageDir)) {
            throw new RuntimeException('ZipArchive::extractTo() returned false');
        }
        $rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($packageDir, FilesystemIterator::SKIP_DOTS));
        foreach ($rii as $f) { if ($f->isFile()) $extractedCount++; }
    } else {
        $tmpExtractDir = $packageDir . '_extract_tmp';
        if (!is_dir($tmpExtractDir)) mkdir($tmpExtractDir, 0755, true);
        if (!$zip->extractTo($tmpExtractDir)) {
            throw new RuntimeException('ZipArchive::extractTo() returned false');
        }
        $srcBase = $tmpExtractDir . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, rtrim($stripPfx, '/'));
        if (is_dir($srcBase)) {
            $rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($srcBase, FilesystemIterator::SKIP_DOTS));
            foreach ($rii as $f) {
                if (!$f->isFile()) continue;
                $rel  = substr($f->getPathname(), strlen($srcBase) + 1);
                $dest = $packageDir . DIRECTORY_SEPARATOR . $rel;
                $ddir = dirname($dest);
                if (!is_dir($ddir)) mkdir($ddir, 0755, true);
                rename($f->getPathname(), $dest);
                $extractedCount++;
            }
        }
        $rii3 = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($tmpExtractDir, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($rii3 as $f3) { $f3->isFile() ? unlink($f3->getPathname()) : rmdir($f3->getPathname()); }
        @rmdir($tmpExtractDir);
    }
} catch (Throwable $e) {
    error_log('[RUN] Extraction failed: ' . $e->getMessage());
    $zip->close();
    @unlink($tmpPath);
    jobUpdate($jobId, 'failed', 'Extraction failed: ' . $e->getMessage(), 0);
    if (!$replaceFlag) rollbackPkg($pkgId);
    exit;
}
$zip->close();
@unlink($tmpPath);

if ($extractedCount === 0) {
    jobUpdate($jobId, 'failed', 'Package contained no readable files.', 0);
    if (!$replaceFlag) rollbackPkg($pkgId);
    exit;
}

error_log("[RUN] Extracted $extractedCount files for pkg=$pkgId");
jobUpdate($jobId, 'running', "Extracted $extractedCount files. Uploading to S3…", 30);

// ── Step 3: S3 Upload ──
if (isS3Configured()) {
    $s3Count  = 0;
    $s3Failed = 0;
    $s3Retry  = [];
    $totalFiles = $extractedCount;
    $doneFiles  = 0;

    try {
        $rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($packageDir, FilesystemIterator::SKIP_DOTS));
        foreach ($rii as $file) {
            if (!$file->isFile()) continue;
            $r    = str_replace(DIRECTORY_SEPARATOR, '/', substr($file->getPathname(), strlen($packageDir) + 1));
            $mime = function_exists('mime_content_type') ? (mime_content_type($file->getPathname()) ?: 'application/octet-stream') : 'application/octet-stream';
            $key  = S3_PREFIX . $pkgId . '/' . $r;
            if (s3PutFile($file->getPathname(), $key, $mime)) {
                $s3Count++;
            } else {
                $s3Retry[] = ['path' => $file->getPathname(), 'key' => $key, 'mime' => $mime, 'rel' => $r];
                error_log('[RUN] S3 upload failed (will retry): ' . $r);
            }
            $doneFiles++;
            if ($doneFiles % 5 === 0 || $doneFiles === $totalFiles) {
                $pct = 30 + (int)(($doneFiles / max(1, $totalFiles)) * 50);
                jobUpdate($jobId, 'running', "Uploading to S3: $doneFiles / $totalFiles files…", $pct);
            }
        }
    } catch (Throwable $s3Err) {
        error_log('[RUN] S3 upload error: ' . $s3Err->getMessage());
    }

    if (!empty($s3Retry)) {
        sleep(2);
        error_log('[RUN] Retrying ' . count($s3Retry) . ' failed S3 uploads…');
        $stillFailed = [];
        foreach ($s3Retry as $item) {
            if (s3PutFile($item['path'], $item['key'], $item['mime'])) {
                $s3Count++;
            } else {
                $stillFailed[] = $item;
                error_log('[RUN] Retry FAILED: ' . $item['rel']);
            }
        }
        $s3Failed = count($stillFailed);
    }

    // Verification pass
    $s3Gaps = [];
    try {
        $rii2 = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($packageDir, FilesystemIterator::SKIP_DOTS));
        foreach ($rii2 as $file2) {
            if (!$file2->isFile()) continue;
            $r2   = str_replace(DIRECTORY_SEPARATOR, '/', substr($file2->getPathname(), strlen($packageDir) + 1));
            $key2 = S3_PREFIX . $pkgId . '/' . $r2;
            if (!s3Exists($key2)) {
                $s3Gaps[] = ['path' => $file2->getPathname(), 'key' => $key2, 'rel' => $r2];
            }
        }
    } catch (Throwable $verifyErr) {
        error_log('[RUN] S3 verification scan error: ' . $verifyErr->getMessage());
    }

    if (!empty($s3Gaps)) {
        error_log('[RUN] Verification found ' . count($s3Gaps) . ' gaps — uploading…');
        foreach ($s3Gaps as $gap) {
            $mime = function_exists('mime_content_type') ? (mime_content_type($gap['path']) ?: 'application/octet-stream') : 'application/octet-stream';
            if (s3PutFile($gap['path'], $gap['key'], $mime)) {
                $s3Count++;
            } else {
                $s3Failed++;
                error_log('[RUN] Gap fill FAILED: ' . $gap['rel']);
            }
        }
    }

    error_log("[RUN] S3 complete: $s3Count uploaded, $s3Failed failed, " . count($s3Gaps) . " gaps filled");
}

jobUpdate($jobId, 'running', 'S3 upload complete. Parsing manifest…', 85);

// ── Step 4: Parse manifest → sco_items ──
try {
    $pdo = getDbConnection();

    $manifestXml = $pdo->query("SELECT manifest_xml FROM scorm_packages WHERE id=$pkgId")->fetchColumn();
    if (!$manifestXml) {
        throw new RuntimeException('manifest_xml missing from scorm_packages row');
    }

    $dom = new DOMDocument();
    libxml_use_internal_errors(true);
    $dom->loadXML($manifestXml);
    $xp = new DOMXPath($dom);
    $xp->registerNamespace('adlcp', 'http://www.adlnet.org/xsd/adlcp_rootv1p2');
    $xp->registerNamespace('adlcp2004', 'http://www.adlnet.org/xsd/adlcp_v1p3');
    $xp->registerNamespace('imsss', 'http://www.imsproject.org/xsd/imsss');
    $xp->registerNamespace('sco', 'http://www.imsproject.org/xsd/imsss');

    $resourceNodes = $xp->query('//*[local-name()="resource"]');
    $scoCount = 0;
    $firstLaunchScoId = null;
    $firstLaunchHref = '';
    $activityTree = [];
    $resourceMetadata = [];

    foreach ($resourceNodes as $resNode) {
        $type          = $resNode->getAttribute('type') ?: 'asset';
        $identifier    = $resNode->getAttribute('identifier') ?: '';
        $identifierref = $resNode->getAttribute('identifierref') ?: '';
        $launchHref    = $resNode->getAttribute('href') ?: '';

        if ($stripPfx !== '' && strpos($launchHref, $stripPfx) === 0) {
            $launchHref = substr($launchHref, strlen($stripPfx));
        }

        $scormType = 'asset';
        if (stripos($type, 'sco') !== false) {
            $scormType = 'sco';
        } else {
            $scoTypeAttr = $resNode->getAttribute('adlcp:scormType');
            if ($scoTypeAttr === '') $scoTypeAttr = $resNode->getAttribute('sco:scormType');
            if (stripos($scoTypeAttr, 'sco') !== false) $scormType = 'sco';
        }
        if ($scormType !== 'sco' && $launchHref !== '') $scormType = 'sco';
        if ($launchHref === '' && $scormType === 'sco') {
            $fileNodes = $xp->query('*[local-name()="file"]', $resNode);
            if ($fileNodes->length > 0) $launchHref = $fileNodes->item(0)->getAttribute('href') ?: '';
        }

        $itemTitle = '';
        $itemNodes = $xp->query('//*[local-name()="item" and @identifierref="' . htmlspecialchars($identifier, ENT_QUOTES) . '"]');
        if ($itemNodes->length > 0) {
            $titleNode = $xp->query('.//*[local-name()="title"]', $itemNodes->item(0))->item(0);
            $itemTitle = $titleNode ? trim($titleNode->textContent) : '';
        }
        if ($itemTitle === '') $itemTitle = $identifier ?: 'SCO';

        $dataFromLms  = $resNode->getAttribute('adlcp:datafromlms') ?: $resNode->getAttribute('datafromlms');
        $prereq       = $resNode->getAttribute('adlcp:prerequisites') ?: $resNode->getAttribute('prerequisites');
        $maxTime      = $resNode->getAttribute('adlcp:maxtimeallowed') ?: $resNode->getAttribute('maxtimeallowed');
        $timeLimitAct = $resNode->getAttribute('adlcp:timelimitaction') ?: $resNode->getAttribute('timelimitaction');
        $ms           = $resNode->getAttribute('adlcp:masteryscore') ?: $resNode->getAttribute('masteryscore');
        $mastery      = ($ms !== '') ? (float)$ms : null;

        // Manifest-derived metadata for the package fingerprint.
        $activityTree[] = ['identifier' => $identifier, 'identifierref' => $identifierref, 'title' => $itemTitle, 'type' => $scormType];
        $resourceMetadata[] = ['identifier' => $identifier, 'type' => $type, 'href' => $launchHref, 'scormType' => $scormType];

        $pdo->prepare("INSERT INTO sco_items
            (package_id, identifier, identifierref, title, launch_url, scorm_type,
             data_from_lms, prerequisites, max_time_allowed, time_limit_action, mastery_score)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
            ->execute([$pkgId, $identifier, $identifierref, $itemTitle, $launchHref, $scormType,
                       $dataFromLms, $prereq, $maxTime, $timeLimitAct, $mastery]);

        if ($scormType === 'sco' && $firstLaunchScoId === null) {
            $firstLaunchScoId = (int)$pdo->lastInsertId();
            $firstLaunchHref = $launchHref;
        }
        $scoCount++;
    }

    if ($firstLaunchScoId !== null) {
        // ── Edition detection + package fingerprint ──
        // Everything here is manifest-driven; launch hrefs always come from
        // <resource href> (never hardcoded index.html/indexapi.html/etc).
        $edition = scormDetectEdition($manifestXml);
        $schemaVersion = strpos($edition, '2004') === 0 ? '2004' : '1.2';
        $rootEl = $dom->documentElement;
        $manifestId = $rootEl->getAttribute('identifier') ?: '';
        $svNode = $xp->query('//*[local-name()="schemaversion"]')->item(0);
        $packageVersion = $svNode ? trim($svNode->textContent) : '';

        // Content hash: stable over the sorted file list + sizes, so identical
        // re-uploads yield the same fingerprint while edits change it.
        $hashParts = [];
        $riiH = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($packageDir, FilesystemIterator::SKIP_DOTS));
        foreach ($riiH as $hf) {
            if (!$hf->isFile()) continue;
            $hashParts[] = str_replace(DIRECTORY_SEPARATOR, '/', substr($hf->getPathname(), strlen($packageDir) + 1)) . ':' . $hf->getSize();
        }
        sort($hashParts, SORT_STRING);
        $contentHash = hash('sha256', implode("\n", $hashParts));

        $fingerprint = json_encode([
            'standard'     => $schemaVersion,
            'edition'      => $edition,
            'launch_href'  => $firstLaunchHref,
            'manifest_id'  => $manifestId,
            'sco_count'    => $scoCount,
            'content_hash' => $contentHash,
            'asset_count'  => $extractedCount,
        ]);

        $pdo->prepare("UPDATE scorm_packages SET
                launch_sco_id = ?, upload_path = ?, status = 'active',
                scorm_edition = ?, manifest_id = ?, package_version = ?, sco_count = ?,
                activity_tree = ?, resource_metadata = ?, content_hash = ?, fingerprint = ?
                WHERE id = ?")
            ->execute([
                $firstLaunchScoId,
                'content/scorm/' . $pkgId,
                $edition,
                $manifestId,
                $packageVersion,
                $scoCount,
                json_encode($activityTree),
                json_encode($resourceMetadata),
                $contentHash,
                $fingerprint,
                $pkgId,
            ]);
    } else {
        $pdo->prepare("UPDATE scorm_packages SET upload_path=?, status='active' WHERE id=?")
            ->execute(['content/scorm/' . $pkgId, $pkgId]);
    }

    error_log("[RUN] Manifest parsed: $scoCount SCOs, firstLaunchScoId=$firstLaunchScoId");

    // Assign to org if stored in job
    $orgId = $job['org_id'] ?? null;
    if ($orgId) {
        try {
            $pdo->prepare("INSERT IGNORE INTO course_assignments (package_id, organization_id, assigned_by) VALUES (?, ?, ?)")
                ->execute([$pkgId, $orgId, $job['user_id'] ?? 0]);
        } catch (Throwable $_) {}
    }

    jobUpdate($jobId, 'done', 'Upload complete.', 100, [
        'package_id'      => $pkgId,
        'sco_count'       => $scoCount,
        'files_extracted' => $extractedCount,
        'launch_sco_id'   => $firstLaunchScoId,
    ]);
    error_log("[RUN] Job $jobId done. pkg=$pkgId scos=$scoCount");

} catch (Throwable $e) {
    error_log('[RUN] Manifest parse failed: ' . $e->getMessage());
    jobUpdate($jobId, 'failed', 'Manifest parse failed: ' . $e->getMessage(), 0);
}
